name: Secure Configurations Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Run Security Scripts
        run: |
          python secure_config_deployment_extended.py

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests
